version: "3"
services:
  web:
    build: .
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      SECRET_KEY: $SECRET_KEY
      TOKEN_EXPIRATION_PERIOD: $TOKEN_EXPIRATION_PERIOD
    ports:
      - "80:8000"
    links:
      - postgres:database
    volumes:
      - ./target/:/usr/src/app/target/

  postgres:
    image: postgres:10.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      # Persist data when container is shut down.
      - /var/opt/amazestats-data:/var/lib/postgresql/data

  openapi:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      URL: http://localhost/openapi/spec.yml
