version: "3"
services:
  dev:
    build: .
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "80:8000"
    links:
      - postgres:database
    volumes:
      - ./target/:/usr/src/app/target/

  postgres:
    image: postgres:10.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      # Persist data when container is shut down.
      - /var/opt/wolley-data:/var/lib/postgresql/data

      # Scripts found in `/docker-entrypoint-initdb.d/` are executed once the
      # postgres data volume is empty.
      - ./resources/sql/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql
      - ./resources/sql/data.sql:/docker-entrypoint-initdb.d/002-data.sql

  openapi:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      URL: http://localhost/openapi/spec.yml
