CREATE TABLE IF NOT EXISTS divisions(
  id SERIAL PRIMARY KEY,
  key VARCHAR(50) UNIQUE,
  name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS teams(
  id SERIAL PRIMARY KEY,
  division INTEGER REFERENCES divisions(id),
  name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS matches(
  id SERIAL PRIMARY KEY,
  division INTEGER REFERENCES divisions(id),
  home_team INTEGER REFERENCES teams(id),
  away_Team INTEGER REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS sets(
  id SERIAL PRIMARY KEY,
  match INTEGER REFERENCES matches(id),
  home_score INTEGER,
  away_score INTEGER
);
